### ISSUE TITLE
Integrating TChan Examples

### ISSUE THREAD

**Issue by bigs** [lotz84/haskellbyexample#1]
Nice project -- I think this is a nice way for someone new to Haskell to jump right into some interesting examples.

One thing kind of stood out for me -- the bits on channels do not actually describe channels. An `MVar` can only hold one value at a time and its access is lock driven. Most people prefer the transactional cousin, `TVar`. Following that, there is actually a very complete transactional channel implementation in the `stm` package that offers the same functionality as go channels (unbounded FIFO queue). You can find out more about them [here](https://hackage.haskell.org/package/stm-2.4.4/docs/Control-Concurrent-STM-TChan.html).

I think it'd be best to demonstrate use of `TChan`s in your example. Furthermore, it does support non-blocking polling via `tryPeekTChan` and `tryReadTChan`.

**Comment by lotz84** [comment]
Thank you for giving me good advice!
I updated topics of concurenncy using STM. SInce I have learned that `TQueue` is faster than `TChan`, I use `TQueue` mainly :)
27099fdb
